# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: 201405118/order-service-app:1.0
        ports:
        - containerPort: 8080
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: order-spring-boot-k8
spec:
  selector:
    app: order-service
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000